### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by osindex** [StoneGroup/stone#3]
web模式
```shell
[crit] 25856#0: *158950 connect() to unix:/var/run/stone-web-fpm.sock failed (2: No such file or directory)
```
service模式
权限不足。

然后，很多文档的命名空间还是 qufenxi。

最后 这个项目不维护了么？

**Comment by chefxu** [comment]
默认运行需要root权限，因为需要往系统目录里写sock文件，并且会以指定用户运行。 
文档是以之前的代码为例写的， 后来由于公司原因项目被要求删除，我重新发布的一个版本。

目前我司线上业务已经没有在用了，所以不会有太多精力在这个项目上了， sorry。
