### ISSUE TITLE
server模式怎么获取POST请求的json数据？file_get_contents("php://input")获取不到

### ISSUE THREAD

**Issue by FradeDeng** [StoneGroup/stone#4]
server模式下，在Handler里面的process方法中调用file_get_contents("php://input")无法返回post的row data

**Comment by chefxu** [comment]
php://input 是只读的， 无法重写， 所以不能通过它来获取。 试试 "$_SERVER['HTTP_RAW_POST']" 看看吧。

**Comment by FradeDeng** [comment]
这个方法很有效，已经解决了我的问题。
非常感谢你的帮助！
最后，你写的Stone真是太赞了，简单好用，我这边项目的并发量提升了12倍！
