### ISSUE TITLE
composer安装的时候出错

### ISSUE THREAD

**Issue by jacky8899** [StoneGroup/stone#5]
[Composer\Downloader\TransportException]                                                                                                                      
  The "https://codeload.github.com/StoneGroup/stone/legacy.zip/ad9e178684058ab569f73e4e88f4ab4a0715683a" file could not be downloaded (HTTP/1.1 404 Not Found)

另外runkit 在centos 7, php 7.1下面要用这个脚本安装：
```
git clone https://github.com/runkit7/runkit7.git
cd runkit7
phpize
# The sandbox related code and flags have been removed, no need to disable them.
# (--enable-runkit-modify (on by default) controls function, method, class, manipulation, and will control property manipulation)
# (--enable-runkit-super (on by default) allows you to add custom superglobals)
./configure
make
make test
sudo make install
```

**Comment by chefxu** [comment]
1. 我刚才试了下 `composer require stone/kernel:dev-master`， 是可以成功下载的。 看起来可能是你的composer环境的问题。
2. 另外， 使用runkit是实验性质的， 注意风险。
3. 本项目不会再投入太多精力， 可考虑 laravel-s
