### ISSUE TITLE
stone-web-fpm.sock 这个文件在哪有啊

### ISSUE THREAD

**Issue by olives006** [StoneGroup/stone#6]
# fastcgi_pass             unix:/data/bvuYZmzU/sites/sw.yug.one/php-pool/php-fpm.sock;
   fastcgi_pass 		   unix:/data/bvuYZmzU/sites/sw.yug.one/php-pool/stone-web-fpm.sock; # Stone

**Comment by chefxu** [comment]
服务启动时生成的， 如果没有检查下配置和目录权限。
